begin;
insert into public.categories(slug,name,sort_order) values
('brewing','Brewing',0),
('kettles','Kettles',1),
('grinders','Grinders',2),
('scales','Scales',3),
('latte-art','Latte Art',4),
('drinkware','Drinkware',5),
('cleaning','Cleaning',6),
('lab','Lab',7),
('espresso','Espresso',8)
on conflict(slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.brands(slug,name) values
('hario','Hario'),
('fellow','Fellow'),
('comandante','Comandante'),
('acaia','Acaia'),
('rhinowares','Rhinowares'),
('moccamaster','Moccamaster'),
('pezzetti','Pezzetti'),
('kinto','Kinto'),
('bialetti','Bialetti'),
('aeropress','AeroPress'),
('origami','Origami'),
('epic','Epic'),
('studio-barista','Studio Barista'),
('motta','Motta'),
('cafelat','Cafelat'),
('cafetto','Cafetto'),
('mhw3bomber','MHW3Bomber'),
('varia','Varia'),
('brewista','Brewista'),
('eureka','Eureka')
on conflict(slug) do update set name=excluded.name;
insert into public.products(id,slug,name,category_slug,brand_slug,description,details,price,currency,source_url,rating,review_count,badge,status,stock_quantity,is_b2b,is_featured,sort_order) values
('v60','ceramic-pour-over-dripper','Ceramic Pour Over Dripper','brewing','hario','Size 02 · 1–4 cups','["Size 02 · 1–4 cups","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,39.90,'EUR','https://www.hario-europe.com/products/v60-ceramic-colour-drippers-02',4.9,124,'BESTSELLER','active',0,false,true,0),
('server','hario-v60-glass-server','Hario V60 Glass Server','brewing','hario','600 ml heatproof glass server','["600 ml heatproof glass server","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,16.90,'EUR','https://www.hario-europe.com/products/v60-range-server-clear-600ml',4.8,89,'BESTSELLER','active',0,false,true,1),
('kettle','fellow-stagg-ekg-electric-kettle','Fellow Stagg EKG Electric Kettle','kettles','fellow','Black · precision temperature control','["Black · precision temperature control","Real market reference product","Category: Kettles","Pre-launch demand test"]'::jsonb,189.00,'EUR','https://fellowproducts.com/products/stagg-ekg-electric-pour-over-kettle',4.9,210,null,'active',0,false,false,2),
('grinder','comandante-c40-mk4-manual-grinder','Comandante C40 MK4 Manual Grinder','grinders','comandante','Black · Nitro Blade burr','["Black · Nitro Blade burr","Real market reference product","Category: Grinders","Pre-launch demand test"]'::jsonb,259.00,'EUR','https://comandantegrinder.com/products/c40-mk4',4.9,78,'NEW','active',0,false,true,3),
('scale','acaia-pearl-s-digital-scale','Acaia Pearl S Digital Scale','scales','acaia','Black · 0.1 g precision','["Black · 0.1 g precision","Real market reference product","Category: Scales","Pre-launch demand test"]'::jsonb,169.00,'EUR','https://eu.acaia.co/products/pearl-model-s',4.9,96,null,'active',0,false,false,4),
('pitcher','rhinowares-milk-pitcher-600-ml','Rhinowares Milk Pitcher 600 ml','latte-art','rhinowares','600 ml stainless steel','["600 ml stainless steel","Real market reference product","Category: Latte Art","Pre-launch demand test"]'::jsonb,15.90,'EUR','https://www.complementosdelcafe.com/en/accessories/studio-barista-classic-milk-pitcher-600ml-stainless-steel',4.8,52,null,'active',0,false,false,5),
('moccamaster','moccamaster-kbg-select-copper','Moccamaster KBG Select Copper','brewing','moccamaster','1.25 L · 10 cups','["1.25 L · 10 cups","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,275.00,'EUR','https://www.complementosdelcafe.com/en/brewing/moccamaster-kbg-select-copper',4.9,64,null,'active',0,false,false,6),
('pezzetti','pezzetti-bellexpress-1-cup-black','Pezzetti Bellexpress 1 Cup Black','brewing','pezzetti','Compact aluminium moka pot','["Compact aluminium moka pot","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,17.04,'EUR','https://www.complementosdelcafe.com/en/brewing/pezzetti-moka-belleexpress-1-cup-black',4.7,41,null,'active',0,false,false,7),
('kinto-oct','kinto-oct-brewer-4-cups-white','Kinto OCT Brewer 4 Cups White','brewing','kinto','Porcelain · 4 cups','["Porcelain · 4 cups","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,25.00,'EUR','https://www.complementosdelcafe.com/en/brewing/kinto-oct-brewer-4-cups-white',4.8,57,null,'active',0,false,false,8),
('suiren','hario-v60-suiren-02-black','Hario V60 Suiren 02 Black','brewing','hario','Modular V60 dripper · 2–4 cups','["Modular V60 dripper · 2–4 cups","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,44.59,'EUR','https://www.complementosdelcafe.com/en/v60/hario-v60-suiren-02-black',4.9,73,null,'active',0,false,false,9),
('syphon','hario-coffee-syphon-technica-5','Hario Coffee Syphon Technica 5','brewing','hario','Vacuum brewer · 5 cups','["Vacuum brewer · 5 cups","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,93.78,'EUR','https://www.complementosdelcafe.com/en/brewing/hario-coffee-syphon-technica-5',4.8,49,null,'active',0,false,false,10),
('mizudashi','hario-mizudashi-cold-brew-pot-1000-ml','Hario Mizudashi Cold Brew Pot 1000 ml','brewing','hario','1 L cold brew pitcher','["1 L cold brew pitcher","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,17.55,'EUR','https://www.complementosdelcafe.com/en/brewing/hario-mizudashi-cold-brew-coffee-pot-1000ml-brown',4.8,88,null,'active',0,false,false,11),
('bialetti-black','bialetti-moka-express-6-cups-black','Bialetti Moka Express 6 Cups Black','brewing','bialetti','Classic moka · 6 cups','["Classic moka · 6 cups","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,45.58,'EUR','https://www.complementosdelcafe.com/en/brewing/bialetti-moka-express-6-cups-black',4.8,104,null,'active',0,false,false,12),
('stagg-xf','fellow-stagg-xf-dripper-set','Fellow Stagg XF Dripper Set','brewing','fellow','Dripper, carafe and filters','["Dripper, carafe and filters","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,94.99,'EUR','https://www.complementosdelcafe.com/en/brewing/fellow-dripper-stagg-xf-set',4.9,61,null,'active',0,false,false,13),
('moccamaster-mug','moccamaster-cup-one-mug-300-ml','Moccamaster Cup One Mug 300 ml','drinkware','moccamaster','Ceramic mug · 300 ml','["Ceramic mug · 300 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,18.15,'EUR','https://www.complementosdelcafe.com/en/brewing/moccamaster-cup-one-mug-300ml',4.8,54,null,'active',0,false,false,14),
('aeropress-carafe','aeropress-carafe-600-ml','AeroPress Carafe 600 ml','brewing','aeropress','Clear serving carafe · 600 ml','["Clear serving carafe · 600 ml","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,22.99,'EUR','https://www.complementosdelcafe.com/en/brewing/aeropress-carafe-600ml',4.8,77,null,'active',0,false,false,15),
('moccamaster-kbgt','moccamaster-kbgt-black','Moccamaster KBGT Black','brewing','moccamaster','Thermal filter brewer · 1.25 L','["Thermal filter brewer · 1.25 L","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,269.00,'EUR','https://www.complementosdelcafe.com/en/brewing/moccamaster-kbgt-black',4.9,47,null,'active',0,false,false,16),
('bialetti-induction','bialetti-moka-induction-red-6-cups','Bialetti Moka Induction Red 6 Cups','brewing','bialetti','Induction moka · 6 cups','["Induction moka · 6 cups","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,64.18,'EUR','https://www.complementosdelcafe.com/en/brewing/bialetti-moka-induction-red-6-cups',4.8,92,null,'active',0,false,false,17),
('origami-tea','origami-tea-dripper-matte-beige','Origami Tea Dripper Matte Beige','brewing','origami','Porcelain tea dripper','["Porcelain tea dripper","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,35.03,'EUR','https://www.complementosdelcafe.com/en/brewing/origami-tea-dripper-matte-beige',4.8,39,null,'active',0,false,false,18),
('aeropress-filter','aeropress-stainless-steel-reusable-filter','AeroPress Stainless Steel Reusable Filter','brewing','aeropress','Reusable metal filter','["Reusable metal filter","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,19.00,'EUR','https://www.complementosdelcafe.com/en/brewing/aeropress-stainless-steel-reusable-filter',4.8,83,null,'active',0,false,false,19),
('epic-latte-red','epic-latte-cup-and-saucer-180-ml-red','Epic Latte Cup & Saucer 180 ml Red','drinkware','epic','Porcelain · 180 ml','["Porcelain · 180 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,8.05,'EUR','https://www.complementosdelcafe.com/es/tazas/epic-taza-y-plato-latte-180ml-rojo',4.8,66,null,'active',0,false,false,20),
('epic-latte-blue','epic-latte-cup-and-saucer-180-ml-blue','Epic Latte Cup & Saucer 180 ml Blue','drinkware','epic','Porcelain · 180 ml','["Porcelain · 180 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,8.05,'EUR','https://www.complementosdelcafe.com/es/tazas/epic-taza-y-plato-latte-180ml-azul',4.8,58,null,'active',0,false,false,21),
('epic-latte-black','epic-latte-cup-and-saucer-180-ml-black','Epic Latte Cup & Saucer 180 ml Black','drinkware','epic','Porcelain · 180 ml','["Porcelain · 180 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,8.05,'EUR','https://www.complementosdelcafe.com/es/tazas/epic-taza-y-plato-latte-180ml-negro',4.8,71,null,'active',0,false,false,22),
('epic-latte-grey','epic-latte-cup-and-saucer-180-ml-grey','Epic Latte Cup & Saucer 180 ml Grey','drinkware','epic','Porcelain · 180 ml','["Porcelain · 180 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,8.05,'EUR','https://www.complementosdelcafe.com/es/tazas/epic-taza-y-plato-latte-180ml-gris',4.8,63,null,'active',0,false,false,23),
('pitcher-350','studio-barista-milk-pitcher-350-ml-black','Studio Barista Milk Pitcher 350 ml Black','latte-art','studio-barista','Stainless steel · 350 ml','["Stainless steel · 350 ml","Real market reference product","Category: Latte Art","Pre-launch demand test"]'::jsonb,17.00,'EUR','https://www.complementosdelcafe.com/es/accesorios/studio-barista-jarra-de-leche-clasica-350ml-negra',4.8,75,null,'active',0,false,false,24),
('motta-yellow','motta-tulip-milk-pitcher-500-ml-yellow','Motta Tulip Milk Pitcher 500 ml Yellow','latte-art','motta','Stainless steel · 500 ml','["Stainless steel · 500 ml","Real market reference product","Category: Latte Art","Pre-launch demand test"]'::jsonb,17.18,'EUR','https://www.complementosdelcafe.com/es/accesorios/motta-jarra-de-leche-tulip-500ml-amarillo',4.8,45,null,'active',0,false,false,25),
('cafelat-cloths','cafelat-microfiber-cloth-pack-4','Cafelat Microfiber Cloth Pack · 4','cleaning','cafelat','Four barista cleaning cloths','["Four barista cleaning cloths","Real market reference product","Category: Cleaning","Pre-launch demand test"]'::jsonb,23.34,'EUR','https://www.complementosdelcafe.com/es/limpieza/cafelat-pack-bayetas-microfibra-4-uds',4.8,51,null,'active',0,false,false,26),
('cafetto-gc2','cafetto-gc2-organic-grinder-cleaner-450-g','Cafetto GC2 Organic Grinder Cleaner 450 g','cleaning','cafetto','Organic grinder cleaner · 450 g','["Organic grinder cleaner · 450 g","Real market reference product","Category: Cleaning","Pre-launch demand test"]'::jsonb,19.97,'EUR','https://www.complementosdelcafe.com/es/limpieza/cafetto-gc2-limpiador-organico-molinillos-450g',4.9,109,null,'active',0,false,false,27),
('mhw-pitcher','mhw3bomber-milk-pitcher-3-0-450-ml-purple','MHW3Bomber Milk Pitcher 3.0 450 ml Purple','latte-art','mhw3bomber','Precision latte-art pitcher · 450 ml','["Precision latte-art pitcher · 450 ml","Real market reference product","Category: Latte Art","Pre-launch demand test"]'::jsonb,36.65,'EUR','https://www.complementosdelcafe.com/es/jarras-de-leche/mhw3bomber-jarra-de-leche-30-clasica-450ml-morado',4.9,84,null,'active',0,false,false,28),
('epic-capp-turq','epic-cappuccino-cup-and-saucer-230-ml-turquoise','Epic Cappuccino Cup & Saucer 230 ml Turquoise','drinkware','epic','Porcelain · 230 ml','["Porcelain · 230 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,8.49,'EUR','https://www.complementosdelcafe.com/es/tazas/epic-taza-y-plato-cappuccino-230ml-turquesa',4.8,59,null,'active',0,false,false,29),
('epic-capp-grey','epic-cappuccino-cup-and-saucer-230-ml-grey','Epic Cappuccino Cup & Saucer 230 ml Grey','drinkware','epic','Porcelain · 230 ml','["Porcelain · 230 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,8.49,'EUR','https://www.complementosdelcafe.com/es/tazas/epic-taza-y-plato-cappuccino-230ml-gris',4.8,48,null,'active',0,false,false,30),
('epic-mug','epic-coffee-mug-355-ml-black','Epic Coffee Mug 355 ml Black','drinkware','epic','Ceramic mug · 355 ml','["Ceramic mug · 355 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,7.02,'EUR','https://www.complementosdelcafe.com/es/tazas/epic-cups-coffee-mug-355ml-negro',4.7,44,null,'active',0,false,false,31),
('epic-double','epic-double-cappuccino-280-ml-blue','Epic Double Cappuccino 280 ml Blue','drinkware','epic','Double-wall porcelain · 280 ml','["Double-wall porcelain · 280 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,8.49,'EUR','https://www.complementosdelcafe.com/es/tazas/epic-taza-y-plato-doble-cappuccino-280ml-azul',4.8,42,null,'active',0,false,false,32),
('origami-cupping','origami-coe-cupping-cup','Origami COE Cupping Cup','lab','origami','Porcelain cupping cup · 225 ml','["Porcelain cupping cup · 225 ml","Real market reference product","Category: Lab","Pre-launch demand test"]'::jsonb,10.65,'EUR','https://www.complementosdelcafe.com/es/accesorios/origami-taza-de-cata-coe',4.9,38,null,'active',0,false,false,33),
('carter','fellow-carter-move-3-in-1-16-oz','Fellow Carter Move 3-in-1 16 oz','drinkware','fellow','Ceramic-lined travel mug · 473 ml','["Ceramic-lined travel mug · 473 ml","Real market reference product","Category: Drinkware","Pre-launch demand test"]'::jsonb,53.89,'EUR','https://www.complementosdelcafe.com/es/outdoors/fellow-carter-bundle-move-3-in-1-16oz-negro-mate',4.9,118,null,'active',0,false,false,34),
('bialetti-pink','bialetti-exclusive-6-cups-pastel-pink','Bialetti Exclusive 6 Cups Pastel Pink','brewing','bialetti','Aluminium moka · 6 cups','["Aluminium moka · 6 cups","Real market reference product","Category: Brewing","Pre-launch demand test"]'::jsonb,56.00,'EUR','https://www.complementosdelcafe.com/es/brewing/bialetti-exclusive-6-tazas-rosa-pastel',4.8,72,null,'active',0,false,false,35),
('varia-kettle','varia-smart-kettle-black','Varia Smart Kettle Black','kettles','varia','1 L · precise temperature control','["1 L · precise temperature control","Real market reference product","Category: Kettles","Pre-launch demand test"]'::jsonb,129.99,'EUR','https://www.complementosdelcafe.com/en/accessories/varia-smart-kettle-black',4.8,69,null,'active',0,false,false,36),
('brewista-kettle','brewista-artisan-1l-white-wood','Brewista Artisan 1L White/Wood','kettles','brewista','1 L · variable temperature','["1 L · variable temperature","Real market reference product","Category: Kettles","Pre-launch demand test"]'::jsonb,172.43,'EUR','https://www.complementosdelcafe.com/en/barista-tools/brewista-artisan-1l-kettle-whitewood-white-base',4.8,81,null,'active',0,false,false,37),
('knockbox','studio-barista-wood-and-steel-knock-box','Studio Barista Wood & Steel Knock Box','espresso','studio-barista','Wood and stainless steel','["Wood and stainless steel","Real market reference product","Category: Espresso","Pre-launch demand test"]'::jsonb,30.25,'EUR','https://www.complementosdelcafe.com/es/accesorios/studio-barista-picamarro-de-madera-y-acero',4.8,53,null,'active',0,false,false,38),
('dosing-cup','eureka-dosing-cup-80-g','Eureka Dosing Cup 80 g','espresso','eureka','Stainless steel · 80 g','["Stainless steel · 80 g","Real market reference product","Category: Espresso","Pre-launch demand test"]'::jsonb,33.88,'EUR','https://www.complementosdelcafe.com/es/accesorios/eureka-vaso-dosificador-80g',4.8,46,null,'active',0,false,false,39)
on conflict(id) do update set slug=excluded.slug,name=excluded.name,category_slug=excluded.category_slug,brand_slug=excluded.brand_slug,description=excluded.description,details=excluded.details,price=excluded.price,currency=excluded.currency,source_url=excluded.source_url,rating=excluded.rating,review_count=excluded.review_count,badge=excluded.badge,status=excluded.status,stock_quantity=excluded.stock_quantity,is_b2b=excluded.is_b2b,is_featured=excluded.is_featured,sort_order=excluded.sort_order;
delete from public.product_images where product_id in ('v60','server','kettle','grinder','scale','pitcher','moccamaster','pezzetti','kinto-oct','suiren','syphon','mizudashi','bialetti-black','stagg-xf','moccamaster-mug','aeropress-carafe','moccamaster-kbgt','bialetti-induction','origami-tea','aeropress-filter','epic-latte-red','epic-latte-blue','epic-latte-black','epic-latte-grey','pitcher-350','motta-yellow','cafelat-cloths','cafetto-gc2','mhw-pitcher','epic-capp-turq','epic-capp-grey','epic-mug','epic-double','origami-cupping','carter','bialetti-pink','varia-kettle','brewista-kettle','knockbox','dosing-cup');
insert into public.product_images(product_id,url,alt_text,position) values
('v60','https://www.hario-europe.com/cdn/shop/products/VDC-02-PUH-EXweb.png?v=1683550130','Ceramic Pour Over Dripper — view 1',0),
('v60','https://www.espressocoffeeshop.com/3826-large_default/hario-v60-dripper-02-ceramica-viola.jpg','Ceramic Pour Over Dripper — view 2',1),
('v60','https://store.crooked.com/cdn/shop/products/Crookedcoffee_pettybrew_productphotography19_FINAL-327551_grande.jpg?v=1707156861','Ceramic Pour Over Dripper — view 3',2),
('v60','https://beanstockcoffee.com/cdn/shop/products/IMG_1343_1024x1024.jpg?v=1636912780','Ceramic Pour Over Dripper — view 4',3),
('server','https://www.hario-europe.com/cdn/shop/files/VFP-1000_web04.png?v=1683557313&width=5760','Hario V60 Glass Server — view 1',0),
('server','https://m.media-amazon.com/images/I/71XndyYqMZL._AC_SL1000_.jpg','Hario V60 Glass Server — view 2',1),
('server','https://hermanoscoffeeroasters.com/cdn/shop/files/hario-600ml-server-product-image.jpg?v=1714657928&width=1445','Hario V60 Glass Server — view 3',2),
('server','https://millennialscoffeepr.com/cdn/shop/products/IMG_5015_42f3c192-0ac3-4698-bf5f-cf31fe6ca288_1024x1024.jpg?v=1588274402','Hario V60 Glass Server — view 4',3),
('kettle','https://fellowproducts.com/cdn/shop/files/Web_PDP_StaggEKGElectricKettle-Pro_Woodland_Walnut_1.png?v=1773351258','Fellow Stagg EKG Electric Kettle — view 1',0),
('kettle','https://images.squarespace-cdn.com/content/v1/611593ff48e9bd20354ddfcb/1700792812072-32XFOO8N8MXALQ08KAAJ/Fellow_Stagg_EKG_05-2aa92c137b7040bebb507f3775a4d9a0.jpg?format=2500w','Fellow Stagg EKG Electric Kettle — view 2',1),
('kettle','https://fstapdltb.filerobot.com/akeneo-belco/RessourceFamilies/equipement_media_dam_to_pim/FELLOW_STAGGEKG_BL_AMB%2B%282%29.jpg?vh=6024c0','Fellow Stagg EKG Electric Kettle — view 3',2),
('kettle','https://www.citiesocial.com/cdn/shop/products/13_346b251c-78a2-451e-a1c1-3cfb92a4994e.jpg?v=1689904271','Fellow Stagg EKG Electric Kettle — view 4',3),
('grinder','https://img.kavosdraugas.lt/40823e04-2069-4760-ae3d-fc9aaa789668/1000x1000/nitro-blade-black4png.jpg','Comandante C40 MK4 Manual Grinder — view 1',0),
('grinder','https://www.rigtigkaffe.dk/28667-thickbox_default/comandante-c40-mk4-kaffemolle-nitro-blade-black.jpg','Comandante C40 MK4 Manual Grinder — view 2',1),
('grinder','https://cdn.shopify.com/s/files/1/0598/1202/0375/products/squareblack_2000x_9b611b88-5747-4966-9619-93909f115bbf.png?v=1654805181','Comandante C40 MK4 Manual Grinder — view 3',2),
('grinder','https://comandantegrinder.com/cdn/shop/files/slider_02.jpg?v=1741355501&width=2134','Comandante C40 MK4 Manual Grinder — view 4',3),
('scale','https://eu.acaia.co/cdn/shop/files/PearlS_white_3.jpg?v=1768313576','Acaia Pearl S Digital Scale — view 1',0),
('scale','https://eu.acaia.co/cdn/shop/files/PearlS_black_1_1500x.jpg?v=1768313576','Acaia Pearl S Digital Scale — view 2',1),
('scale','https://eu.acaia.co/cdn/shop/products/PearlS2022_1500x1000_03.jpg?v=1739179523&width=1500','Acaia Pearl S Digital Scale — view 3',2),
('scale','https://eu.acaia.co/cdn/shop/products/PearlS2022_1500x1000_04.jpg?v=1739179523&width=1500','Acaia Pearl S Digital Scale — view 4',3),
('pitcher','https://www.complementosdelcafe.com/6927-medium_default/studio-barista-classic-milk-pitcher-600ml-stainless-steel.jpg','Rhinowares Milk Pitcher 600 ml — view 1',0),
('pitcher','https://www.complementosdelcafe.com/6928-medium_default/studio-barista-classic-milk-pitcher-600ml-stainless-steel.jpg','Rhinowares Milk Pitcher 600 ml — view 2',1),
('pitcher','https://www.complementosdelcafe.com/6879-medium_default/studio-barista-classic-milk-pitcher-600ml-stainless-steel.jpg','Rhinowares Milk Pitcher 600 ml — view 3',2),
('pitcher','https://www.complementosdelcafe.com/6905-medium_default/studio-barista-classic-milk-pitcher-600ml-stainless-steel.jpg','Rhinowares Milk Pitcher 600 ml — view 4',3),
('moccamaster','https://nano-kaffee.de/cdn/shop/files/KBGSelectCopper.jpg?v=1732010415','Moccamaster KBG Select Copper — view 1',0),
('moccamaster','https://www.barista.gr/images/thumbs/0298938_W-4.jpg','Moccamaster KBG Select Copper — view 2',1),
('moccamaster','https://brewinggadgets.in/cdn/shop/files/MOCCAMASTER_KBG_COPPER_9.webp?v=1760536209&width=1946','Moccamaster KBG Select Copper — view 3',2),
('moccamaster','https://brewinggadgets.in/cdn/shop/files/MOCCAMASTER_KBG_COPPER_8.webp?v=1760536209&width=1445','Moccamaster KBG Select Copper — view 4',3),
('pezzetti','https://www.complementosdelcafe.com/3864-medium_default/pezzetti-moka-belleexpress-1-cup-black.jpg','Pezzetti Bellexpress 1 Cup Black — view 1',0),
('pezzetti','https://finesio.b-cdn.net/product-pim/1/4/3/9/143914eba92e9683d6e8d65473fdd02b57f6aad1_178632_packshot.jpg?class=public','Pezzetti Bellexpress 1 Cup Black — view 2',1),
('pezzetti','https://finesio.b-cdn.net/product-pim/0/6/6/2/0662d76829d1f3bfd428a2bfc3bf2c956591f288_178632_narrow_arrange.jpg?class=public','Pezzetti Bellexpress 1 Cup Black — view 3',2),
('pezzetti','https://roomplus.co.za/cdn/shop/files/pezzetti-ital-express-stove-top-coffee-maker-black-9894221_2048x.jpg?v=1758030134','Pezzetti Bellexpress 1 Cup Black — view 4',3),
('kinto-oct','https://www.complementosdelcafe.com/4953-medium_default/kinto-oct-brewer-4-cups-white.jpg','Kinto OCT Brewer 4 Cups White — view 1',0),
('kinto-oct','https://www.complementosdelcafe.com/4951-medium_default/kinto-oct-brewer-4-cups-white.jpg','Kinto OCT Brewer 4 Cups White — view 2',1),
('kinto-oct','https://www.complementosdelcafe.com/4952-medium_default/kinto-oct-brewer-4-cups-white.jpg','Kinto OCT Brewer 4 Cups White — view 3',2),
('kinto-oct','https://kinto-europe.com/cdn/shop/files/oct_21ss_003_sq-v1649771174780.jpg?v=1756721825&width=1024','Kinto OCT Brewer 4 Cups White — view 4',3),
('suiren','https://www.complementosdelcafe.com/5496-medium_default/hario-v60-suiren-02-black.jpg','Hario V60 Suiren 02 Black — view 1',0),
('suiren','https://www.complementosdelcafe.com/5497-medium_default/hario-v60-suiren-02-black.jpg','Hario V60 Suiren 02 Black — view 2',1),
('suiren','https://www.complementosdelcafe.com/5498-medium_default/hario-v60-suiren-02-black.jpg','Hario V60 Suiren 02 Black — view 3',2),
('suiren','https://product.hstatic.net/200000038436/product/pheu-pha-ca-phe-hario-v60-suiren-vdsu-09_04139b7fe5924b12873c73af3a007223_master.png','Hario V60 Suiren 02 Black — view 4',3),
('syphon','https://www.complementosdelcafe.com/3224-medium_default/hario-coffee-syphon-technica-5.jpg','Hario Coffee Syphon Technica 5 — view 1',0),
('syphon','https://www.complementosdelcafe.com/3222-medium_default/hario-coffee-syphon-technica-5.jpg','Hario Coffee Syphon Technica 5 — view 2',1),
('syphon','https://www.complementosdelcafe.com/3221-medium_default/hario-coffee-syphon-technica-5.jpg','Hario Coffee Syphon Technica 5 — view 3',2),
('syphon','https://www.complementosdelcafe.com/3223-medium_default/hario-coffee-syphon-technica-5.jpg','Hario Coffee Syphon Technica 5 — view 4',3),
('mizudashi','https://www.complementosdelcafe.com/3502-medium_default/hario-mizudashi-cold-brew-coffee-pot-1000ml-brown.jpg','Hario Mizudashi Cold Brew Pot 1000 ml — view 1',0),
('mizudashi','https://www.complementosdelcafe.com/3505-medium_default/hario-mizudashi-cold-brew-coffee-pot-1000ml-brown.jpg','Hario Mizudashi Cold Brew Pot 1000 ml — view 2',1),
('mizudashi','https://www.complementosdelcafe.com/3503-medium_default/hario-mizudashi-cold-brew-coffee-pot-1000ml-brown.jpg','Hario Mizudashi Cold Brew Pot 1000 ml — view 3',2),
('mizudashi','https://www.complementosdelcafe.com/3504-medium_default/hario-mizudashi-cold-brew-coffee-pot-1000ml-brown.jpg','Hario Mizudashi Cold Brew Pot 1000 ml — view 4',3),
('bialetti-black','https://www.complementosdelcafe.com/2048-medium_default/bialetti-moka-express-6-cups-black.jpg','Bialetti Moka Express 6 Cups Black — view 1',0),
('bialetti-black','https://www.complementosdelcafe.com/2046-medium_default/bialetti-moka-express-6-cups-black.jpg','Bialetti Moka Express 6 Cups Black — view 2',1),
('bialetti-black','https://www.complementosdelcafe.com/2047-medium_default/bialetti-moka-express-6-cups-black.jpg','Bialetti Moka Express 6 Cups Black — view 3',2),
('bialetti-black','https://capecoffeebeans.co.za/cdn/shop/files/moka_6_cup_exclusive_black_grande.jpg?v=1776762114','Bialetti Moka Express 6 Cups Black — view 4',3),
('stagg-xf','https://www.complementosdelcafe.com/2438-medium_default/fellow-dripper-stagg-xf-set.jpg','Fellow Stagg XF Dripper Set — view 1',0),
('stagg-xf','https://www.complementosdelcafe.com/2439-medium_default/fellow-dripper-stagg-xf-set.jpg','Fellow Stagg XF Dripper Set — view 2',1),
('stagg-xf','https://www.complementosdelcafe.com/2437-medium_default/fellow-dripper-stagg-xf-set.jpg','Fellow Stagg XF Dripper Set — view 3',2),
('stagg-xf','https://fellowproducts.com/cdn/shop/files/Web_PDP_2_Stagg_XF_Pour-OverSet_HowItWorks_Desktop.jpg?v=1773326540&width=1420','Fellow Stagg XF Dripper Set — view 4',3),
('moccamaster-mug','https://www.complementosdelcafe.com/5331-medium_default/moccamaster-cup-one-mug-300ml.jpg','Moccamaster Cup One Mug 300 ml — view 1',0),
('moccamaster-mug','https://www.complementosdelcafe.com/3358-medium_default/moccamaster-cup-one-mug-300ml.jpg','Moccamaster Cup One Mug 300 ml — view 2',1),
('moccamaster-mug','https://www.complementosdelcafe.com/3359-medium_default/moccamaster-cup-one-mug-300ml.jpg','Moccamaster Cup One Mug 300 ml — view 3',2),
('moccamaster-mug','https://www.complementosdelcafe.com/3360-medium_default/moccamaster-cup-one-mug-300ml.jpg','Moccamaster Cup One Mug 300 ml — view 4',3),
('aeropress-carafe','https://www.complementosdelcafe.com/1907-medium_default/aeropress-carafe-600ml.jpg','AeroPress Carafe 600 ml — view 1',0),
('aeropress-carafe','https://www.complementosdelcafe.com/1904-medium_default/aeropress-carafe-600ml.jpg','AeroPress Carafe 600 ml — view 2',1),
('aeropress-carafe','https://www.complementosdelcafe.com/1906-medium_default/aeropress-carafe-600ml.jpg','AeroPress Carafe 600 ml — view 3',2),
('aeropress-carafe','https://www.complementosdelcafe.com/1905-medium_default/aeropress-carafe-600ml.jpg','AeroPress Carafe 600 ml — view 4',3),
('moccamaster-kbgt','https://www.complementosdelcafe.com/3309-medium_default/moccamaster-kbgt-black.jpg','Moccamaster KBGT Black — view 1',0),
('moccamaster-kbgt','https://www.complementosdelcafe.com/3310-medium_default/moccamaster-kbgt-black.jpg','Moccamaster KBGT Black — view 2',1),
('moccamaster-kbgt','https://cdn11.bigcommerce.com/s-f5f38/images/stencil/1080x1080/products/2733/17628/image__22382.1759496421.png?c=2','Moccamaster KBGT Black — view 3',2),
('moccamaster-kbgt','https://us.moccamaster.com/cdn/shop/files/KBGTBlack02_MidnightEdit_1_2048x.jpg?v=1770054702','Moccamaster KBGT Black — view 4',3),
('bialetti-induction','https://www.complementosdelcafe.com/2089-medium_default/bialetti-moka-induction-red-6-cups.jpg','Bialetti Moka Induction Red 6 Cups — view 1',0),
('bialetti-induction','https://http2.mlstatic.com/D_NQ_NP_994338-MLC106609375166_022026-O.webp','Bialetti Moka Induction Red 6 Cups — view 2',1),
('bialetti-induction','https://www.yagos.it/37060-thickbox_default/Caffettiera-Bialetti-Moka-Induction-rosso.jpg','Bialetti Moka Induction Red 6 Cups — view 3',2),
('bialetti-induction','https://cdn.idealo.com/folder/Product/200760/1/200760152/s1_produktbild_max/bialetti-moka-induktion-6-tassen-rot-0006946.jpg','Bialetti Moka Induction Red 6 Cups — view 4',3),
('origami-tea','https://www.complementosdelcafe.com/5573-medium_default/origami-tea-dripper-matte-beige.jpg','Origami Tea Dripper Matte Beige — view 1',0),
('origami-tea','https://www.complementosdelcafe.com/5574-medium_default/origami-tea-dripper-matte-beige.jpg','Origami Tea Dripper Matte Beige — view 2',1),
('origami-tea','https://www.mujostore.com/cdn/shop/files/origami-dripper-S-matte-beige-7.jpg?v=1739352706','Origami Tea Dripper Matte Beige — view 3',2),
('origami-tea','https://www.mujostore.com/cdn/shop/files/origami-wood-dripper-holder-acacia-dripper-S-matte-beige.jpg?v=1739352706&width=3840','Origami Tea Dripper Matte Beige — view 4',3),
('aeropress-filter','https://www.complementosdelcafe.com/1921-medium_default/aeropress-stainless-steel-reusable-filter.jpg','AeroPress Stainless Steel Reusable Filter — view 1',0),
('aeropress-filter','https://www.complementosdelcafe.com/1924-medium_default/aeropress-stainless-steel-reusable-filter.jpg','AeroPress Stainless Steel Reusable Filter — view 2',1),
('aeropress-filter','https://www.complementosdelcafe.com/1922-medium_default/aeropress-stainless-steel-reusable-filter.jpg','AeroPress Stainless Steel Reusable Filter — view 3',2),
('aeropress-filter','https://www.complementosdelcafe.com/1923-medium_default/aeropress-stainless-steel-reusable-filter.jpg','AeroPress Stainless Steel Reusable Filter — view 4',3),
('epic-latte-red','https://www.complementosdelcafe.com/6825-medium_default/epic-taza-y-plato-latte-180ml-rojo.jpg','Epic Latte Cup & Saucer 180 ml Red — view 1',0),
('epic-latte-red','https://www.complementosdelcafe.com/6831-medium_default/epic-taza-y-plato-latte-180ml-rojo.jpg','Epic Latte Cup & Saucer 180 ml Red — view 2',1),
('epic-latte-red','https://beanbros.co/cdn/shop/files/epic-latte-cup-with-plate-180ml-758815.jpg?v=1723743546&width=1080','Epic Latte Cup & Saucer 180 ml Red — view 3',2),
('epic-latte-red','https://beanbros.co/cdn/shop/files/epic-latte-cup-with-plate-180ml-273438.jpg?v=1723743546&width=1000','Epic Latte Cup & Saucer 180 ml Red — view 4',3),
('epic-latte-blue','https://www.complementosdelcafe.com/4642-medium_default/epic-taza-y-plato-latte-180ml-azul.jpg','Epic Latte Cup & Saucer 180 ml Blue — view 1',0),
('epic-latte-blue','https://www.complementosdelcafe.com/6820-medium_default/epic-taza-y-plato-latte-180ml-azul.jpg','Epic Latte Cup & Saucer 180 ml Blue — view 2',1),
('epic-latte-blue','https://beanbros.co/cdn/shop/files/epic-latte-cup-with-plate-180ml-758815.jpg?v=1723743546&width=1080','Epic Latte Cup & Saucer 180 ml Blue — view 3',2),
('epic-latte-blue','https://beanbros.co/cdn/shop/files/epic-latte-cup-with-plate-180ml-273438.jpg?v=1723743546&width=1000','Epic Latte Cup & Saucer 180 ml Blue — view 4',3),
('epic-latte-black','https://www.complementosdelcafe.com/4649-medium_default/epic-taza-y-plato-latte-180ml-negro.jpg','Epic Latte Cup & Saucer 180 ml Black — view 1',0),
('epic-latte-black','https://www.complementosdelcafe.com/6839-medium_default/epic-taza-y-plato-latte-180ml-negro.jpg','Epic Latte Cup & Saucer 180 ml Black — view 2',1),
('epic-latte-black','https://mkfresh.pl/hpeciai/2b85eb234c65d50b6afa70871b38f24c/pol_pl_Czarna-filizanka-do-kawy-EPIC-180-ml-11794_1.jpg','Epic Latte Cup & Saucer 180 ml Black — view 3',2),
('epic-latte-black','https://beanbros.co/cdn/shop/files/epic-latte-cup-with-plate-180ml-273438.jpg?v=1723743546&width=1000','Epic Latte Cup & Saucer 180 ml Black — view 4',3),
('epic-latte-grey','https://www.complementosdelcafe.com/4648-medium_default/epic-taza-y-plato-latte-180ml-gris.jpg','Epic Latte Cup & Saucer 180 ml Grey — view 1',0),
('epic-latte-grey','https://www.complementosdelcafe.com/6854-medium_default/epic-taza-y-plato-latte-180ml-gris.jpg','Epic Latte Cup & Saucer 180 ml Grey — view 2',1),
('epic-latte-grey','https://beanbros.co/cdn/shop/files/epic-latte-cup-with-plate-180ml-758815.jpg?v=1723743546&width=1080','Epic Latte Cup & Saucer 180 ml Grey — view 3',2),
('epic-latte-grey','https://beanbros.co/cdn/shop/files/epic-latte-cup-with-plate-180ml-273438.jpg?v=1723743546&width=1000','Epic Latte Cup & Saucer 180 ml Grey — view 4',3),
('pitcher-350','https://www.complementosdelcafe.com/6923-medium_default/studio-barista-jarra-de-leche-clasica-350ml-negra.jpg','Studio Barista Milk Pitcher 350 ml Black — view 1',0),
('pitcher-350','https://www.complementosdelcafe.com/5102-medium_default/studio-barista-jarra-de-leche-clasica-350ml-negra.jpg','Studio Barista Milk Pitcher 350 ml Black — view 2',1),
('pitcher-350','https://www.complementosdelcafe.com/5101-medium_default/studio-barista-jarra-de-leche-clasica-350ml-negra.jpg','Studio Barista Milk Pitcher 350 ml Black — view 3',2),
('pitcher-350','https://www.complementosdelcafe.com/5100-medium_default/studio-barista-jarra-de-leche-clasica-350ml-negra.jpg','Studio Barista Milk Pitcher 350 ml Black — view 4',3),
('motta-yellow','https://www.complementosdelcafe.com/4850-medium_default/motta-jarra-de-leche-tulip-500ml-amarillo.jpg','Motta Tulip Milk Pitcher 500 ml Yellow — view 1',0),
('motta-yellow','https://coffeestuff.co.nz/cdn/shop/files/motta-tulip-milk-frothing-jug-500ml-yellow-2.jpg?v=1779068408&width=1946','Motta Tulip Milk Pitcher 500 ml Yellow — view 2',1),
('motta-yellow','https://coffeestuff.co.nz/cdn/shop/files/motta-tulip-milk-frothing-jug-500ml-yellow-3.jpg?v=1779068400&width=1946','Motta Tulip Milk Pitcher 500 ml Yellow — view 3',2),
('motta-yellow','https://coffeestuff.co.nz/cdn/shop/files/motta-tulip-milk-frothing-jug-500ml-yellow-4.jpg?v=1779068425&width=1946','Motta Tulip Milk Pitcher 500 ml Yellow — view 4',3),
('cafelat-cloths','https://www.complementosdelcafe.com/4813-medium_default/cafelat-pack-4-panos-microfibra.jpg','Cafelat Microfiber Cloth Pack · 4 — view 1',0),
('cafelat-cloths','https://area51coffeeroasters.com/wp-content/uploads/Gear-CafelatMicrofiberCloths_4pack-P01-1080w.png','Cafelat Microfiber Cloth Pack · 4 — view 2',1),
('cafelat-cloths','https://area51coffeeroasters.com/wp-content/uploads/Gear-CafelatMicrofiberCloths_4pack-SL01-1080w.png','Cafelat Microfiber Cloth Pack · 4 — view 3',2),
('cafelat-cloths','https://area51coffeeroasters.com/wp-content/uploads/Gear-CafelatMicrofiberCloths_4pack-SL02-1080w.png','Cafelat Microfiber Cloth Pack · 4 — view 4',3),
('cafetto-gc2','https://ineffablecoffee.com/cdn/shop/files/cafetto-gc2-450g.webp?crop=center&height=900&v=1750680228&width=900','Cafetto GC2 Organic Grinder Cleaner 450 g — view 1',0),
('cafetto-gc2','https://kaffemester-i03.mycdn.no/mysimgprod/kaffemester_mystore_no/images/wJx1U_Cafetto_Cafetto_GC2_Grinder_Clean_1.webp/w800h800.webp','Cafetto GC2 Organic Grinder Cleaner 450 g — view 2',1),
('cafetto-gc2','https://cdn.cafetto.com/general-images/grinder-clean.jpg','Cafetto GC2 Organic Grinder Cleaner 450 g — view 3',2),
('cafetto-gc2','https://www.jhornig.com/cdn/shop/articles/jhornig-muehlenreinigung-blogbeitrag-1_1200x800.jpg?v=1741614769','Cafetto GC2 Organic Grinder Cleaner 450 g — view 4',3),
('mhw-pitcher','https://www.complementosdelcafe.com/5806-medium_default/mhw3bomber-jarra-de-leche-30-clasica-450ml-morado.jpg','MHW3Bomber Milk Pitcher 3.0 450 ml Purple — view 1',0),
('mhw-pitcher','https://www.complementosdelcafe.com/5809-medium_default/mhw3bomber-jarra-de-leche-30-clasica-450ml-morado.jpg','MHW3Bomber Milk Pitcher 3.0 450 ml Purple — view 2',1),
('mhw-pitcher','https://www.complementosdelcafe.com/5808-medium_default/mhw3bomber-jarra-de-leche-30-clasica-450ml-morado.jpg','MHW3Bomber Milk Pitcher 3.0 450 ml Purple — view 3',2),
('mhw-pitcher','https://www.complementosdelcafe.com/5807-medium_default/mhw3bomber-jarra-de-leche-30-clasica-450ml-morado.jpg','MHW3Bomber Milk Pitcher 3.0 450 ml Purple — view 4',3),
('epic-capp-turq','https://www.complementosdelcafe.com/4777-medium_default/epic-taza-y-plato-cappuccino-230ml-turquesa.jpg','Epic Cappuccino Cup & Saucer 230 ml Turquoise — view 1',0),
('epic-capp-turq','https://www.complementosdelcafe.com/6858-medium_default/epic-taza-y-plato-cappuccino-230ml-turquesa.jpg','Epic Cappuccino Cup & Saucer 230 ml Turquoise — view 2',1),
('epic-capp-turq','https://beanbros.co/cdn/shop/files/epic-cappuccino-cup-with-plate-230ml-129591.jpg?v=1723743547','Epic Cappuccino Cup & Saucer 230 ml Turquoise — view 3',2),
('epic-capp-turq','https://beanbros.co/cdn/shop/files/epic-cappuccino-cup-with-plate-230ml-302116.jpg?v=1723743547','Epic Cappuccino Cup & Saucer 230 ml Turquoise — view 4',3),
('epic-capp-grey','https://www.complementosdelcafe.com/4772-medium_default/epic-taza-y-plato-cappuccino-230ml-gris.jpg','Epic Cappuccino Cup & Saucer 230 ml Grey — view 1',0),
('epic-capp-grey','https://www.complementosdelcafe.com/6855-medium_default/epic-taza-y-plato-cappuccino-230ml-gris.jpg','Epic Cappuccino Cup & Saucer 230 ml Grey — view 2',1),
('epic-capp-grey','https://beanbros.co/cdn/shop/files/epic-cappuccino-cup-with-plate-230ml-180495.jpg?v=1723743547','Epic Cappuccino Cup & Saucer 230 ml Grey — view 3',2),
('epic-capp-grey','https://beanbros.co/cdn/shop/files/epic-cappuccino-cup-with-plate-230ml-939914.jpg?v=1723743548','Epic Cappuccino Cup & Saucer 230 ml Grey — view 4',3),
('epic-mug','https://beanbros.co/cdn/shop/files/epic-mug-355ml-694888.jpg?v=1723743542&width=1080','Epic Coffee Mug 355 ml Black — view 1',0),
('epic-mug','https://beanbros.co/cdn/shop/files/epic-mug-355ml-370672.jpg?v=1723743543&width=1000','Epic Coffee Mug 355 ml Black — view 2',1),
('epic-mug','https://www.barista-pro.com/wp-content/uploads/epic-coffee-mug-black.jpg','Epic Coffee Mug 355 ml Black — view 3',2),
('epic-mug','https://www.barista-pro.com/wp-content/uploads/epic-mug-black-lifestyle.jpg','Epic Coffee Mug 355 ml Black — view 4',3),
('epic-double','https://www.complementosdelcafe.com/4786-medium_default/epic-taza-y-plato-doble-cappuccino-280ml-azul.jpg','Epic Double Cappuccino 280 ml Blue — view 1',0),
('epic-double','https://www.complementosdelcafe.com/6822-medium_default/epic-taza-y-plato-doble-cappuccino-280ml-azul.jpg','Epic Double Cappuccino 280 ml Blue — view 2',1),
('epic-double','https://beanbros.co/cdn/shop/files/epic-cappuccino-cup-with-plate-230ml-129591.jpg?v=1723743547','Epic Double Cappuccino 280 ml Blue — view 3',2),
('epic-double','https://beanbros.co/cdn/shop/files/epic-cappuccino-cup-with-plate-230ml-302116.jpg?v=1723743547','Epic Double Cappuccino 280 ml Blue — view 4',3),
('origami-cupping','https://www.complementosdelcafe.com/5926-medium_default/origami-taza-de-cata-coe.jpg','Origami COE Cupping Cup — view 1',0),
('origami-cupping','https://www.complementosdelcafe.com/5928-medium_default/origami-taza-de-cata-coe.jpg','Origami COE Cupping Cup — view 2',1),
('origami-cupping','https://www.complementosdelcafe.com/5927-medium_default/origami-taza-de-cata-coe.jpg','Origami COE Cupping Cup — view 3',2),
('origami-cupping','https://www.roguewavecoffee.ca/cdn/shop/products/OrigamiCuppingBowl_1024x1024.jpg','Origami COE Cupping Cup — view 4',3),
('carter','https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4a714bc1-c4bb-47df-87a5-6ddaec80b13e.jpg','Fellow Carter Move 3-in-1 16 oz — view 1',0),
('carter','https://ihygge.hk/cdn/shop/files/Matte_Black_Move__Cold__and_Carry_-_yythkg.png?v=1723706270','Fellow Carter Move 3-in-1 16 oz — view 2',1),
('carter','https://www1.yohohongkong.com/images/upload/Proddb/1708335623110328313.jpg','Fellow Carter Move 3-in-1 16 oz — view 3',2),
('carter','https://fellowproducts.com/cdn/shop/files/022724_Website_Compare_Carter_Page_Desert_Capsule_Module__2x_08115247-3df8-4f67-9331-fc04376fda33.png?v=1709138061&width=1560','Fellow Carter Move 3-in-1 16 oz — view 4',3),
('bialetti-pink','https://www.complementosdelcafe.com/2095-medium_default/bialetti-exclusive-6-tazas-rosa-pastel.jpg','Bialetti Exclusive 6 Cups Pastel Pink — view 1',0),
('bialetti-pink','https://www.bialetti.com/media/catalog/product/cache/7/image/1200x/17f82f742ffe127f42dca9de82fb58b1/m/o/moka_exclusive_pink_6tazze.jpg','Bialetti Exclusive 6 Cups Pastel Pink — view 2',1),
('bialetti-pink','https://cdn.shopify.com/s/files/1/0513/5342/8667/files/bialetti-moka-exclusive-pink-6-cup.jpg','Bialetti Exclusive 6 Cups Pastel Pink — view 3',2),
('bialetti-pink','https://www.maxicoffee.com/images/products/bialetti-exclusive-rose-6-tasses.jpg','Bialetti Exclusive 6 Cups Pastel Pink — view 4',3),
('varia-kettle','https://www.variabrewing.com/cdn/shop/files/AURA0.8LBLK.jpg?v=1716393149','Varia Smart Kettle Black — view 1',0),
('varia-kettle','https://www.variabrewing.com/cdn/shop/files/AURA0.8L-BLK-FLUX_cce2633b-3279-4198-8f91-31ec9a3274d9.png?v=1732337918','Varia Smart Kettle Black — view 2',1),
('varia-kettle','https://www.variabrewing.com/cdn/shop/files/AURA_BLACK_SIDE.jpg','Varia Smart Kettle Black — view 3',2),
('varia-kettle','https://www.variabrewing.com/cdn/shop/files/AURA_BLACK_LIFESTYLE.jpg','Varia Smart Kettle Black — view 4',3),
('brewista-kettle','https://www.complementosdelcafe.com/2108-medium_default/brewista-artisan-1l-kettle-whitewood-white-base.jpg','Brewista Artisan 1L White/Wood — view 1',0),
('brewista-kettle','https://www.complementosdelcafe.com/2109-medium_default/brewista-artisan-1l-kettle-whitewood-white-base.jpg','Brewista Artisan 1L White/Wood — view 2',1),
('brewista-kettle','https://cdn.shopify.com/s/files/1/0445/6912/2719/products/BrewistaArtisanWhiteWood_1024x1024.jpg','Brewista Artisan 1L White/Wood — view 3',2),
('brewista-kettle','https://www.creativecoffee.ca/images/products/brewista-artisan-white-wood-lifestyle.jpg','Brewista Artisan 1L White/Wood — view 4',3),
('knockbox','https://www.complementosdelcafe.com/4201-medium_default/studio-barista-picamarro-de-madera-y-acero.jpg','Studio Barista Wood & Steel Knock Box — view 1',0),
('knockbox','https://www.complementosdelcafe.com/4202-medium_default/studio-barista-picamarro-de-madera-y-acero.jpg','Studio Barista Wood & Steel Knock Box — view 2',1),
('knockbox','https://www.complementosdelcafe.com/4203-medium_default/studio-barista-picamarro-de-madera-y-acero.jpg','Studio Barista Wood & Steel Knock Box — view 3',2),
('knockbox','https://beanbros.co/cdn/shop/files/studio-barista-knock-box-wood-steel.jpg','Studio Barista Wood & Steel Knock Box — view 4',3),
('dosing-cup','https://www.complementosdelcafe.com/2356-medium_default/eureka-vaso-dosificador-80g.jpg','Eureka Dosing Cup 80 g — view 1',0),
('dosing-cup','https://www.complementosdelcafe.com/2357-medium_default/eureka-vaso-dosificador-80g.jpg','Eureka Dosing Cup 80 g — view 2',1),
('dosing-cup','https://www.eureka.co.it/public/prodotti/immagini/dosing-cup-80g-1.jpg','Eureka Dosing Cup 80 g — view 3',2),
('dosing-cup','https://www.eureka.co.it/public/prodotti/immagini/dosing-cup-80g-2.jpg','Eureka Dosing Cup 80 g — view 4',3);
commit;
