import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import SeoSiteHeader from '../../../components/SeoSiteHeader';
import {catalog40} from '../../../lib/catalog40';
import {SITE_URL,categoryCopy,categorySlug,productSlug} from '../../../lib/seo';

type Props={params:Promise<{slug:string}>};
const categories=[...new Set(catalog40.map(p=>p.category))];
const findCategory=(slug:string)=>categories.find(c=>categorySlug(c)===slug);
export function generateStaticParams(){return categories.map(c=>({slug:categorySlug(c)}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const c=findCategory(slug);if(!c)return {};const seo=categoryCopy[c];const description=seo?.description||`Shop ${c.toLowerCase()} specialty coffee equipment in Europe.`;return {title:seo?.title||`${c} Coffee Equipment Europe`,description,keywords:seo?.keywords,alternates:{canonical:`/categories/${slug}`},openGraph:{type:'website',url:`/categories/${slug}`,title:seo?.title||`${c} Coffee Equipment Europe`,description},twitter:{card:'summary',title:seo?.title||`${c} Coffee Equipment Europe`,description}}}
export default async function CategoryPage({params}:Props){const {slug}=await params;const c=findCategory(slug);if(!c)notFound();const products=catalog40.filter(p=>p.category===c);const seo=categoryCopy[c];const url=`${SITE_URL}/categories/${slug}`;const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:SITE_URL},{'@type':'ListItem',position:2,name:c,item:url}]};const list={'@context':'https://schema.org','@type':'ItemList',name:seo?.title||c,itemListElement:products.map((p,i)=>({'@type':'ListItem',position:i+1,url:`${SITE_URL}/products/${productSlug(p)}`,name:p.name}))};return <><SeoSiteHeader/><main className="seoPage"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(list)}}/><nav className="seoBreadcrumb"><Link href="/">Home</Link><span>›</span><span>{c}</span></nav><h1>{seo?.title||`${c} Coffee Equipment Europe`}</h1><p>{seo?.intro||seo?.description}</p><div className="seoGrid">{products.map(p=><Link className="seoCard" key={p.id} href={`/products/${productSlug(p)}`}><img src={`/api/product-image?id=${encodeURIComponent(p.id)}&variant=0&v=seo2`} width="320" height="320" loading="lazy" alt={`${p.name} — ${c.toLowerCase()} coffee equipment`}/><div className="seoCardText"><strong>{p.name}</strong><small>€{p.price.toFixed(2)} · {p.description}</small></div></Link>)}</div><section className="seoSection"><h2>Shop specialty coffee equipment in Europe</h2><p>BREW / OBJECTS brings together specialist coffee gear for European home brewers, baristas and cafés. Compare products by brewing method, workflow and use case, then explore individual product pages for specifications and reference pricing.</p><div className="seoLinks"><Link href="/">All coffee equipment</Link>{categories.filter(x=>x!==c).map(x=><Link key={x} href={`/categories/${categorySlug(x)}`}>{x}</Link>)}</div></section></main></>}
