'use client';
import {useEffect,useMemo,useState} from 'react';
import {catalog40,CatalogProduct} from '../lib/catalog40';
import {track} from '../lib/analytics';

type CartItem=CatalogProduct&{qty:number};
const KEY='brew-objects-cart-v3';
const money=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n);
const photo=(p:CatalogProduct)=>`/api/product-image?url=${encodeURIComponent(p.source)}`;
const categoryOrder=['All','Brewing','Espresso','Grinders','Kettles','Scales','Latte Art','Drinkware','Cleaning','Lab'];
const categoryCards=[
 ['Pour Over','Brewing','v60'],['Espresso','Espresso','dosing-cup'],['Grinders','Grinders','grinder'],['Kettles','Kettles','kettle'],['Scales','Scales','scale'],['Latte Art','Latte Art','pitcher'],['Drinkware','Drinkware','epic-latte-grey'],['Cleaning','Cleaning','cafetto-gc2'],['Lab','Lab','origami-cupping'],['New','All','suiren']
] as const;
const byId=(id:string)=>catalog40.find(p=>p.id===id)!;

export default function Store40(){
 const[category,setCategory]=useState('All');
 const[query,setQuery]=useState('');
 const[cart,setCart]=useState<CartItem[]>([]);
 const[selected,setSelected]=useState<CatalogProduct|null>(null);
 const[cartOpen,setCartOpen]=useState(false);
 const[checkout,setCheckout]=useState(false);
 const[wholesale,setWholesale]=useState(false);
 useEffect(()=>{try{const x=localStorage.getItem(KEY);if(x)setCart(JSON.parse(x))}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(cart))}catch{}},[cart]);
 const filtered=useMemo(()=>catalog40.filter(p=>(category==='All'||p.category===category)&&(`${p.name} ${p.description}`.toLowerCase().includes(query.trim().toLowerCase()))),[category,query]);
 const count=cart.reduce((s,x)=>s+x.qty,0),subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);
 const add=(p:CatalogProduct)=>{setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});setCartOpen(true);track('add_to_cart',{product_id:p.id,price:p.price,currency:'EUR'})};
 const qty=(id:string,d:number)=>setCart(c=>c.flatMap(i=>i.id!==id?[i]:i.qty+d<=0?[]:[{...i,qty:i.qty+d}]));
 const choose=(c:string)=>{setCategory(c);setTimeout(()=>document.getElementById('shop')?.scrollIntoView({behavior:'smooth'}),0)};
 const hero=[byId('kettle'),byId('grinder'),byId('scale')];
 const related=selected?catalog40.filter(p=>p.id!==selected.id&&(p.category===selected.category||p.category==='Brewing')).slice(0,4):[];
 return <>
  <div className="topbar"><span>◎ Ship to: Europe⌄</span><span>Pre-launch: special prices for early supporters</span><button onClick={()=>setWholesale(true)}>B2B / Wholesale</button></div>
  <header><a className="brand" href="#">BREW / OBJECTS<small>Specialty coffee tools</small></a><nav className="mainnav"><button onClick={()=>choose('Brewing')}>Brewing</button><button onClick={()=>choose('Espresso')}>Espresso</button><button onClick={()=>choose('Latte Art')}>Latte Art</button><button onClick={()=>choose('Drinkware')}>Drinkware</button><button onClick={()=>choose('Cleaning')}>Cleaning</button></nav><div className="headtools"><label className="search"><input aria-label="Search products" placeholder="Search tools..." value={query} onChange={e=>setQuery(e.target.value)}/><span>⌕</span></label><button className="iconbtn" aria-label="Wishlist">♡</button><button className="cart" onClick={()=>setCartOpen(true)}>Cart <b>{count}</b></button></div></header>
  <main>
   <section className="hero refHero"><div className="heroCopy"><h1>Objects for<br/>better coffee.</h1><p className="lead">Carefully selected specialty coffee tools<br/>for home brewers and cafés across Europe.</p><div className="actions"><a className="primary" href="#shop">Shop all products</a><button className="secondary" onClick={()=>setWholesale(true)}>B2B / Wholesale</button></div></div><div className="heroProducts">{hero.map(p=><div className="heroProduct" key={p.id}><img src={photo(p)} alt={p.name}/></div>)}</div><div className="heroBenefits refBenefits"><span>🚚 <b>Fast shipping across Europe</b><small>Free shipping over €60</small></span><span>✦ <b>Premium quality</b><small>Selected specialty gear</small></span><span>□ <b>For home & professional use</b><small>Tools that make a difference</small></span><span>♧ <b>B2B for cafés</b><small>Wholesale enquiries welcome</small></span></div></section>
   <section className="categories"><div className="sectionTitle"><h3>Top Categories</h3><a href="#shop">View all categories →</a></div><div className="catrow ten">{categoryCards.map(([label,c,id])=>{const p=byId(id);return <button key={label} onClick={()=>choose(c)}><span className="catimg"><img src={photo(p)} alt={label}/></span><small>{label}</small></button>})}</div></section>
   <section id="shop" className="shop"><aside className="filters"><div className="filterHead"><b>Filter</b><button onClick={()=>{setCategory('All');setQuery('')}}>Clear all</button></div><div className="filterBlock"><b>Category</b>{categoryOrder.filter(c=>c!=='All').map(c=><label key={c}><input type="checkbox" checked={category===c} onChange={()=>setCategory(category===c?'All':c)}/>{c} ({catalog40.filter(p=>p.category===c).length})</label>)}</div><div className="filterBlock"><b>Price</b><div className="rangeLine"/><small>€0 <span>€300+</span></small></div><div className="filterBlock"><b>Use</b><label><input type="checkbox"/>Home</label><label><input type="checkbox"/>Café / B2B</label></div></aside><div className="catalog"><div className="catalogHead"><h2>{filtered.length} products</h2><select aria-label="Sort products"><option>Sort by: Featured</option><option>Price: low to high</option><option>Price: high to low</option></select></div><div className="chips">{categoryOrder.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="grid six">{filtered.map((p,i)=><article key={p.id}><button className="productMain" onClick={()=>{setSelected(p);track('view_item',{product_id:p.id})}}><div className="pic realPic"><img src={photo(p)} alt={p.name} loading="lazy"/>{p.badge&&<span className="badge">{p.badge}</span>}<span className="heart">♡</span></div><div className="meta"><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><div className="rating"><span>★★★★★</span><small>({p.reviews})</small></div></div></button><div className="buy"><strong>{money(p.price)}</strong><button className="plus" aria-label={`Add ${p.name} to cart`} onClick={()=>add(p)}>+</button></div></article>)}</div></div></section>
   <section className="serviceStrip"><span>◇ <b>Pre-launch prices</b><small>Reference pricing for validation</small></span><span>♢ <b>European launch</b><small>Testing demand across the EU</small></span><span>▣ <b>Secure checkout</b><small>No payment collected in prototype</small></span><span>◉ <b>Need help?</b><small>hello@brewobjects.com</small></span></section>
  </main>
  {selected&&<div className="overlay" onMouseDown={()=>setSelected(null)}><div className="productPage refProduct" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><div className="thumbs">{[0,1,2,3].map(i=><div key={i}><img src={photo(selected)} alt=""/></div>)}</div><div className="gallery realGallery"><img src={photo(selected)} alt={selected.name}/></div><div className="info"><p className="eyebrow">{selected.badge||selected.category}</p><h2>{selected.name}</h2><div className="rating"><span>★★★★★</span><small>{selected.rating} · {selected.reviews} reviews</small></div><strong className="price">{money(selected.price)}</strong><p className="tax">Reference market price for this validation storefront.</p><p className="productLead">{selected.description}</p><div className="featureIcons"><span>✓ Real market SKU</span><span>◌ Specialty coffee</span><span>◇ EU reference</span><span>☕ Home & café</span></div><div className="purchase"><label>QUANTITY <span><button type="button">−</button>1<button type="button">+</button></span></label><button className="primary wide" onClick={()=>add(selected)}>Add to cart · {money(selected.price)}</button><button className="secondary wide" onClick={()=>setCheckout(true)}>Buy now</button></div><div className="wholesaleBox"><b>For cafés & professionals</b><small>Tell us what you would buy and in what quantity.</small><button onClick={()=>setWholesale(true)}>Request wholesale pricing</button></div><div className="detailsTabs"><b>Details</b><span>Specifications</span><span>Shipping & Returns</span></div><p className="productCopy">This storefront uses a real market reference product to validate demand. Stock, supplier, final price and commercial terms will be verified before an actual launch.</p><ul className="specs">{selected.details.map(x=><li key={x}>{x}</li>)}</ul><div className="related"><h3>You may also like</h3><div>{related.map(r=><button key={r.id} onClick={()=>setSelected(r)}><span><img src={photo(r)} alt={r.name}/></span><b>{r.name}</b><small>{money(r.price)}</small></button>)}</div></div></div></div></div>}
  {cartOpen&&<div className="overlay" onMouseDown={()=>setCartOpen(false)}><aside className="cartDrawer" onMouseDown={e=>e.stopPropagation()}><div className="drawerhead"><h2>Your cart</h2><button onClick={()=>setCartOpen(false)}>×</button></div>{cart.length===0?<p>Your cart is empty.</p>:<>{cart.map(i=><div className="cartitem" key={i.id}><img src={photo(i)} alt=""/><div><strong>{i.name}</strong><small>{money(i.price)}</small><div className="qty"><button onClick={()=>qty(i.id,-1)}>−</button><span>{i.qty}</span><button onClick={()=>qty(i.id,1)}>+</button></div></div></div>)}<div className="subtotal"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><button className="primary wide" onClick={()=>{setCheckout(true);setCartOpen(false);track('begin_checkout',{value:subtotal})}}>Continue to checkout</button></>}</aside></div>}
  {checkout&&<div className="overlay"><div className="modal"><button className="x" onClick={()=>setCheckout(false)}>×</button><h2>Pre-launch checkout</h2><p>No payment is collected in this validation prototype.</p><form onSubmit={e=>{e.preventDefault();track('checkout_contact_submit',{value:subtotal});setCheckout(false)}}><input type="email" placeholder="Email" required/><input placeholder="Shipping country" required/><button className="primary wide">Continue</button></form></div></div>}
  {wholesale&&<div className="overlay"><div className="modal"><button className="x" onClick={()=>setWholesale(false)}>×</button><h2>Wholesale</h2><form onSubmit={e=>{e.preventDefault();track('wholesale_lead');setWholesale(false)}}><input placeholder="Café / Company" required/><input type="email" placeholder="Email" required/><input placeholder="Country" required/><textarea placeholder="Products and approximate quantities" required/><button className="primary wide">Request pricing</button></form></div></div>}
 </>;
}
