'use client';
import {useEffect,useState} from 'react';
import {track} from '../lib/analytics';

type P={id:string;name:string;category:string;price:number;image:string;description:string;rating:string;reviews:number;badge?:string;details:string[]};
type CartItem=P&{qty:number};
const money=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n);
const KEY='brew-objects-cart-v2';
const products:P[]=[
{id:'v60',name:'Ceramic Pour Over Dripper',category:'Brewing',price:24.9,image:'https://cdn.hands.net/images/4977642143364-1.jpg',description:'Size 02 · 1–4 cups',rating:'4.9',reviews:124,badge:'BESTSELLER',details:['High-quality ceramic body','Spiral ribs for controlled flow','Compatible with V60-style 02 filters','Dishwasher safe']},
{id:'server',name:'Hario V60 Glass Server',category:'Brewing',price:16.9,image:'https://www.hario-europe.com/cdn/shop/products/XGS-80TB_web.png?crop=center&height=800&v=1680526732&width=800',description:'600 ml heatproof glass server',rating:'4.8',reviews:89,badge:'BESTSELLER',details:['Heatproof glass','600 ml capacity','Microwave safe','Dishwasher safe']},
{id:'kettle',name:'Fellow Stagg EKG Electric Kettle',category:'Brewing',price:189,image:'https://www.watchandpuck.sg/cdn/shop/products/fellow-stagg-ekg-electric-kettle-electric-pour-over-kettle-for-coffee-lovers-temperature-control-09l-775369.jpg?v=1738052045&width=1445',description:'Black · precision temperature control',rating:'4.9',reviews:210,details:['Gooseneck precision spout','Variable temperature control','0.9 L capacity','Electric base']},
{id:'grinder',name:'Comandante C40 MK4 Manual Grinder',category:'Espresso Tools',price:259,image:'https://comandantegrinder.com/cdn/shop/files/c40-nitro-blade-mk4-black.jpg?v=1741195167&width=1200',description:'Black · Nitro Blade burr',rating:'4.9',reviews:78,badge:'NEW',details:['Nitro Blade burr','Made in Germany','Manual precision grinder','Two bean jars included']},
{id:'scale',name:'Acaia Pearl S Digital Scale',category:'Brewing',price:169,image:'https://eu.acaia.co/cdn/shop/files/PearlS_black_1.jpg?v=1768313576&width=1500',description:'Black · 0.1 g precision',rating:'4.9',reviews:96,details:['0.1 g readability','Real-time flow-rate display','USB-C rechargeable','Bluetooth 5.0']},
{id:'pitcher',name:'Rhinowares Milk Pitcher',category:'Latte Art',price:15.9,image:'https://www.kamikava.cz/fotky31548/fotos/_vyr_245_Rhinowares-Classic-600-ml.jpg',description:'600 ml stainless steel',rating:'4.8',reviews:52,details:['600 ml volume','Food-grade stainless steel','Latte-art spout','Ergonomic handle']}
];
const cats=[['Pour Over',products[0].image],['Espresso',products[3].image],['Grinders',products[3].image],['Kettles',products[2].image],['Scales',products[4].image],['Latte Art',products[5].image],['Drinkware',products[0].image],['Storage',products[4].image],['Cleaning',products[5].image],['Bundles',products[1].image]];

export default function Store(){
 const[cart,setCart]=useState<CartItem[]>([]);const[cartOpen,setCartOpen]=useState(false);const[selected,setSelected]=useState<P|null>(null);const[wholesale,setWholesale]=useState(false);const[checkout,setCheckout]=useState(false);
 useEffect(()=>{try{const x=localStorage.getItem(KEY);if(x)setCart(JSON.parse(x))}catch{}},[]);useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(cart))},[cart]);
 const count=cart.reduce((a,b)=>a+b.qty,0),subtotal=cart.reduce((a,b)=>a+b.price*b.qty,0);
 const add=(p:P)=>{setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});setCartOpen(true);track('add_to_cart',{product_id:p.id,price:p.price})};
 const qty=(id:string,d:number)=>setCart(c=>c.flatMap(i=>i.id!==id?[i]:i.qty+d<=0?[]:[{...i,qty:i.qty+d}]));
 return <>
 <div className="topbar"><span>◎ Ship to: Europe⌄</span><span>Pre-launch: special prices for early supporters</span><button onClick={()=>setWholesale(true)}>B2B / Wholesale</button></div>
 <header><a className="brand" href="#">BREW / OBJECTS<small>Specialty coffee tools</small></a><nav className="mainnav"><a href="#shop">Brewing</a><a href="#shop">Espresso</a><a href="#shop">Latte Art</a><a href="#shop">Drinkware</a><a href="#shop">Storage</a><a href="#shop">Cleaning</a><a href="#shop">New</a><a href="#shop">Bundles</a></nav><div className="headtools"><label className="search"><input placeholder="Search tools..."/><span>⌕</span></label><button className="iconbtn">♡</button><button className="cart" onClick={()=>setCartOpen(true)}>Cart <b>{count}</b></button></div></header>
 <main>
 <section className="hero refHero"><div className="heroCopy"><h1>Objects for<br/>better coffee.</h1><p className="lead">Carefully selected specialty coffee tools<br/>for home brewers and cafés across Europe.</p><div className="actions"><a className="primary" href="#shop">Shop all products</a><button className="secondary" onClick={()=>setWholesale(true)}>B2B / Wholesale</button></div></div><div className="heroProducts">{[products[0],products[2],products[3],products[4]].map(p=><div className="heroProduct" key={p.id}><img src={p.image} alt={p.name}/></div>)}</div><div className="heroBenefits refBenefits"><span>🚚 <b>Fast shipping across Europe</b><small>Free shipping over €60</small></span><span>✦ <b>Premium quality</b><small>Selected by coffee professionals</small></span><span>□ <b>For home & professional use</b><small>Tools that make a difference</small></span><span>♧ <b>Sustainable choices</b><small>Durable, repairable, responsible</small></span></div></section>
 <section className="categories"><div className="sectionTitle"><h3>Top Categories</h3><a href="#shop">View all categories →</a></div><div className="catrow ten">{cats.map(([n,u])=><button key={n}><span className="catimg"><img src={u} alt={n}/></span><small>{n}</small></button>)}</div></section>
 <section id="shop" className="shop"><aside className="filters"><div className="filterHead"><b>Filter</b><button>Clear all</button></div><div className="filterBlock"><b>Category</b><label><input type="checkbox"/>Pour Over (12)</label><label><input type="checkbox"/>Espresso (8)</label><label><input type="checkbox"/>Grinders (5)</label><label><input type="checkbox"/>Kettles (4)</label><label><input type="checkbox"/>Scales (3)</label><span>Show more</span></div><div className="filterBlock"><b>Price</b><div className="rangeLine"/><small>€0 <span>€350+</span></small></div><div className="filterBlock"><b>Brand</b></div></aside><div className="catalog"><div className="catalogHead"><h2>30 products</h2><select><option>Sort by: Featured</option></select></div><div className="grid six">{products.map(p=><article key={p.id}><button className="productMain" onClick={()=>setSelected(p)}><div className="pic realPic"><img src={p.image} alt={p.name}/>{p.badge&&<span className="badge">{p.badge}</span>}<span className="heart">♡</span></div><div className="meta"><h3>{p.name}</h3><p>{p.description}</p><div className="rating"><span>★★★★★</span><small>({p.reviews})</small></div></div></button><div className="buy"><strong>{money(p.price)}</strong><button className="plus" onClick={()=>add(p)}>+</button></div></article>)}</div></div></section>
 <section className="serviceStrip"><span>◇ <b>Pre-launch prices</b><small>Special prices for early supporters</small></span><span>♢ <b>14-day returns</b><small>Easy returns and exchanges</small></span><span>▣ <b>Secure checkout</b><small>Safe and encrypted payments</small></span><span>◉ <b>Need help?</b><small>hello@brewobjects.com</small></span></section>
 </main>
 {selected&&<div className="overlay" onMouseDown={()=>setSelected(null)}><div className="productPage refProduct" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><div className="thumbs">{[selected.image,selected.image,selected.image,selected.image].map((u,i)=><div key={i}><img src={u} alt=""/></div>)}</div><div className="gallery realGallery"><img src={selected.image} alt={selected.name}/></div><div className="info"><p className="eyebrow">{selected.badge||selected.category}</p><h2>{selected.name}</h2><div className="rating"><span>★★★★★</span><small>{selected.rating} ({selected.reviews})</small></div><strong className="price">{money(selected.price)}</strong><p className="tax">Tax included. Shipping calculated at checkout.</p><p className="productLead">{selected.description}</p><div className="featureIcons"><span>✓ Premium materials</span><span>◌ Easy clean</span><span>◇ Daily use</span><span>☕ Specialty coffee</span></div><div className="purchase"><label>QUANTITY <span><button>−</button>1<button>+</button></span></label><button className="primary wide" onClick={()=>add(selected)}>Add to cart · {money(selected.price)}</button><button className="secondary wide" onClick={()=>setCheckout(true)}>Buy now</button></div><div className="wholesaleBox"><b>For cafés & professionals</b><small>Wholesale prices, custom offers and fast delivery.</small><button onClick={()=>setWholesale(true)}>Request wholesale pricing</button></div><div className="detailsTabs"><b>Details</b><span>Specifications</span><span>Shipping & Returns</span></div><p className="productCopy">Selected as a reference product for our pre-launch demand test. Final sourcing, stock and commercial authorization will be confirmed before sale.</p><ul className="specs">{selected.details.map(x=><li key={x}>{x}</li>)}</ul><div className="related"><h3>You may also like</h3><div>{products.filter(x=>x.id!==selected.id).slice(0,4).map(r=><button key={r.id} onClick={()=>setSelected(r)}><span><img src={r.image} alt={r.name}/></span><b>{r.name}</b><small>{money(r.price)}</small></button>)}</div></div></div></div></div>}
 {cartOpen&&<div className="overlay" onMouseDown={()=>setCartOpen(false)}><aside className="cartDrawer" onMouseDown={e=>e.stopPropagation()}><div className="drawerhead"><h2>Your cart</h2><button onClick={()=>setCartOpen(false)}>×</button></div>{cart.map(i=><div className="cartitem" key={i.id}><img src={i.image} alt=""/><div><strong>{i.name}</strong><small>{money(i.price)}</small><div className="qty"><button onClick={()=>qty(i.id,-1)}>−</button><span>{i.qty}</span><button onClick={()=>qty(i.id,1)}>+</button></div></div></div>)}<div className="subtotal"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><button className="primary wide" onClick={()=>setCheckout(true)}>Continue to checkout</button></aside></div>}
 {checkout&&<div className="overlay"><div className="modal"><button className="x" onClick={()=>setCheckout(false)}>×</button><h2>Pre-launch checkout</h2><p>No payment is collected yet.</p><input placeholder="Email"/><input placeholder="Shipping country"/><button className="primary wide">Continue</button></div></div>}
 {wholesale&&<div className="overlay"><div className="modal"><button className="x" onClick={()=>setWholesale(false)}>×</button><h2>Wholesale</h2><input placeholder="Café / Company"/><input placeholder="Email"/><input placeholder="Country"/><button className="primary wide">Request pricing</button></div></div>}
 </>;
}
