import {catalog40,type CatalogProduct} from './catalog40';
type Row={id:string;slug:string;name:string;price:number|string;currency:string;source_url:string|null;description:string;rating:number|string;reviews:number;badge:string|null;details:unknown;status:string;stock:number|null;is_featured:boolean;is_b2b:boolean;categories:{name:string}|{name:string}[]|null;brands:{name:string}|{name:string}[]|null;product_images:{url:string;position:number;alt:string|null}[]|null};
const endpoint=()=>process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=()=>process.env.SUPABASE_ANON_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const relation=(v:{name:string}|{name:string}[]|null)=>Array.isArray(v)?v[0]?.name:v?.name;
const fallback=():CatalogProduct[]=>catalog40.map(p=>({...p,status:'published',stock:null,isFeatured:Boolean(p.badge),b2b:false}));
const map=(r:Row):CatalogProduct=>({id:r.id,slug:r.slug,name:r.name,category:relation(r.categories)||'Other',brand:relation(r.brands),price:Number(r.price),currency:r.currency||'EUR',source:r.source_url||'',description:r.description,rating:String(r.rating),reviews:r.reviews,badge:r.badge||undefined,details:Array.isArray(r.details)?r.details.map(String):[],images:[...(r.product_images||[])].sort((a,b)=>a.position-b.position),status:r.status,stock:r.stock,isFeatured:r.is_featured,b2b:r.is_b2b});
export async function getProducts():Promise<CatalogProduct[]>{const url=endpoint(),anon=key();if(!url||!anon)return fallback();try{const select='id,slug,name,price,currency,source_url,description,rating,reviews,badge,details,status,stock,is_featured,is_b2b,categories(name),brands(name),product_images(url,position,alt)';const r=await fetch(`${url}/rest/v1/products?select=${encodeURIComponent(select)}&status=eq.published&order=sort_order.asc`,{headers:{apikey:anon,Authorization:`Bearer ${anon}`},next:{revalidate:60}});if(!r.ok)throw new Error(`Supabase catalogue request failed: ${r.status}`);return(await r.json() as Row[]).map(map)}catch(e){console.error(e);return fallback()}}
export async function getProductById(id:string){return(await getProducts()).find(p=>p.id===id)}
export async function getProductBySlug(slug:string){return(await getProducts()).find(p=>(p.slug||'')===slug||p.id===slug)}
