import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import SeoSiteHeader from '../../../components/SeoSiteHeader';
import {catalog40} from '../../../lib/catalog40';
import {SITE_URL,brandDescription,brandFor,brandSlug,categorySlug,productSlug} from '../../../lib/seo';

type Props={params:Promise<{slug:string}>};
const brands=[...new Set(catalog40.map(brandFor))];
const findBrand=(slug:string)=>brands.find(b=>brandSlug(b)===slug);
export function generateStaticParams(){return brands.map(b=>({slug:brandSlug(b)}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const brand=findBrand(slug);if(!brand)return {};const description=brandDescription(brand);return {title:`${brand} Coffee Equipment — Buy in Europe`,description,keywords:[`${brand} Europe`,`${brand} coffee equipment`,`${brand} coffee gear Europe`,`buy ${brand} Europe`,'specialty coffee equipment Europe'],alternates:{canonical:`/brands/${slug}`},openGraph:{type:'website',url:`/brands/${slug}`,title:`${brand} Coffee Equipment — Buy in Europe`,description},twitter:{card:'summary',title:`${brand} Coffee Equipment — Buy in Europe`,description}}}
export default async function BrandPage({params}:Props){const {slug}=await params;const brand=findBrand(slug);if(!brand)notFound();const products=catalog40.filter(p=>brandFor(p)===brand);const url=`${SITE_URL}/brands/${slug}`;const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:SITE_URL},{'@type':'ListItem',position:2,name:brand,item:url}]};const list={'@context':'https://schema.org','@type':'ItemList',name:`${brand} coffee equipment`,itemListElement:products.map((p,i)=>({'@type':'ListItem',position:i+1,url:`${SITE_URL}/products/${productSlug(p)}`,name:p.name}))};return <><SeoSiteHeader/><main className="seoPage"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(list)}}/><nav className="seoBreadcrumb"><Link href="/">Home</Link><span>›</span><span>{brand}</span></nav><div className="seoBrandTitle"><div><h1>{brand} Coffee Equipment in Europe</h1><p>{brandDescription(brand)}</p></div></div><div className="seoGrid">{products.map(p=><Link className="seoCard" key={p.id} href={`/products/${productSlug(p)}`}><img src={`/api/product-image?id=${encodeURIComponent(p.id)}&variant=0&v=seo2`} width="320" height="320" loading="lazy" alt={`${p.name} by ${brand}`}/><div className="seoCardText"><strong>{p.name}</strong><small>€{p.price.toFixed(2)} · {p.category}</small></div></Link>)}</div><section className="seoSection"><h2>Explore {brand} specialty coffee gear</h2><p>Browse {brand} products for specialty coffee brewing and barista workflows. BREW / OBJECTS organizes equipment by product, category and brand so European shoppers and café professionals can compare relevant tools quickly.</p><div className="seoLinks">{[...new Set(products.map(p=>p.category))].map(c=><Link key={c} href={`/categories/${categorySlug(c)}`}>{c}</Link>)}<Link href="/">All products</Link></div></section></main></>}
